---
- hosts: all
  tasks:
    - name: Create file
      become: no
      file:
        dest: ~/hello.txt
        state: touch

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
